name: tanjung_pinang_guide
description: "Aplikasi panduan wisata Tanjung Pinang dengan rekomendasi AI."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0

  # HTTP & API
  http: ^1.2.2

  # Local storage (JWT token)
  shared_preferences: ^2.3.2

  # State management
  provider: ^6.1.2

  # Google Sign-In
  google_sign_in: ^6.2.1

  # Crypto (untuk derive password dari Google ID)
  crypto: ^3.0.3
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  shimmer: ^3.0.0
  pdf: ^3.12.0
  printing: ^5.14.3
  path_provider: ^2.1.6
  cached_network_image: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_blue.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/